layout_spectrum: 0.933942
color:
  saturation: 0.9310929
  lightness: 0.672052
  brandStrength: 0
  brandColors:
    - '#E6F2F2'
    - '#101415'
    - '#B3C9D4'
    - '#568998'
    - '#A3957F'
  rhythmicContrast: 0.7334154
typography_spectrum: 0.2661132
name: Testrhehjjg
